name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          branch: main

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            build-tool: cargo-zigbuild
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            build-tool: cargo-zigbuild
          - target: x86_64-apple-darwin
            os: macos-15-intel
            build-tool: cargo
          - target: aarch64-apple-darwin
            os: macos-latest
            build-tool: cargo
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            build-tool: cargo
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: shuk
          target: ${{ matrix.target }}
          build-tool: ${{ matrix.build-tool }}
          locked: true
          checksum: sha256
          token: ${{ secrets.GITHUB_TOKEN }}
